---
title: "2019-02-01_Gierzynski_NL_MCI"
author: "Nicolas May"
date: "2/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Requirements

## Load Useful Libraries

```{r}
library(dplyr)
```

## Load Useful Variables / Helpers

```{r}
source("~/Desktop/config.R")
rm(BOX_CLIENT_ID); rm(BOX_CLIENT_SECRET); rm(BOX_REDIRECT_URI);
source("~/Desktop/helpers.R")

# switch to access API (TRUE) or not (FALSE)
get_api_data <- TRUE
```

# Get Data

## Define UDS 3 and MiNDSet Data Fields

### UDS 3
```{r}
fields_u3_raw <- c("ptid"
                  , "form_date"
                  , "mrn"
                  , "madc_id"
                  , "dob"
                  , "race"
                  , "sex"
                  , "handed"
                  , "educ"
                  , "maristat"
                  , "mocatots"
                  , "fu_sex"
                  , "fu_maristat"
                  , "fu_mocatots")
fields_u3 <- fields_u3_raw %>% paste(collapse = ",")
```

### MiNDSet Registry
```{r}
fields_ms_raw <- c("subject_id"
                  , "exam_date"
                  , "reg_num" # mrn
                  , "madc_id"
                  , "date"    # rvf date
                  , "first_name"
                  , "last_name"
                  , "street"
                  , "pt_city"
                  , "state"
                  , "zip_code"
                  , "county"
                  , "homephone_number"
                  , "work_phone"
                  , "cell_phone"
                  , "primary_lang"
                  , "so_fname"    # S/O name
                  , "street_name" # S/O street address
                  , "so_city"
                  , "so_state"
                  , "so_zip"
                  , "so_homephone"
                  , "so_workphone"
                  , "so_cellphone"
                  , "so_relationship"
                  , "feedback"
                  , "fb_complete")
fields_ms <- fields_ms_raw %>% paste(collapse = ",")
```

## Retrieve Data via REDCap API

### UDS 3
```{r}
if (get_api_data) {
  json_u3 <- rc_api_get(token  = REDCAP_API_TOKEN_UDS3n,
                        fields = fields_u3)
}

df_u3 <- jsonlite::fromJSON(json_u3) %>% na_if("")
```

### MiNDSet Registry
```{r}
if (get_api_data) {
  json_ms <- rc_api_get(token  = REDCAP_API_TOKEN_MINDSET,
                        fields = fields_ms)
}

df_ms <- jsonlite::fromJSON(json_ms) %>% na_if("")
```

## Write Raw Data to CSV

### UDS 3
```{r}
readr::write_csv(df_u3, "df_u3.csv", na = "")
```

### MiNDSet Registry
```{r}
readr::write_csv(df_ms, "df_ms.csv", na = "")
```




###@    #==--  :  --==#    @##==---==##@##==---==##@    #==--  :  --==#    @###
#==##@    #==-- --==#    @##==---==##@   @##==---==##@    #==-- --==#    @##==#
#--==##@    #==-==#    @##==---==##@   #   @##==---==##@    #==-==#    @##==--#
#=---==##@    #=#    @##==---==##@    #=#    @##==---==##@    #=#    @##==---=#
##==---==##@   #   @##==---==##@    #==-==#    @##==---==##@   #   @##==---==##
#@##==---==##@   @##==---==##@    #==-- --==#    @##==---==##@   @##==---==##@#
#  @##==---==##@##==---==##@    EXTRA  :  SPACE    @##==---==##@##==---==##@  #
#@##==---==##@   @##==---==##@    #==-- --==#    @##==---==##@   @##==---==##@#
##==---==##@   #   @##==---==##@    #==-==#    @##==---==##@   #   @##==---==##
#=---==##@    #=#    @##==---==##@    #=#    @##==---==##@    #=#    @##==---=#
#--==##@    #==-==#    @##==---==##@   #   @##==---==##@    #==-==#    @##==--#
#==##@    #==-- --==#    @##==---==##@   @##==---==##@    #==-- --==#    @##==#
###@    #==--  :  --==#    @##==---==##@##==---==##@    #==--  :  --==#    @###
#==##@    #==-- --==#    @##==---==##@   @##==---==##@    #==-- --==#    @##==#
#--==##@    #==-==#    @##==---==##@   #   @##==---==##@    #==-==#    @##==--#
#=---==##@    #=#    @##==---==##@    #=#    @##==---==##@    #=#    @##==---=#
##==---==##@   #   @##==---==##@    #==-==#    @##==---==##@   #   @##==---==##
#@##==---==##@   @##==---==##@    #==-- --==#    @##==---==##@   @##==---==##@#
#  @##==---==##@##==---==##@    EXTRA  :  SPACE    @##==---==##@##==---==##@  #
#@##==---==##@   @##==---==##@    #==-- --==#    @##==---==##@   @##==---==##@#
##==---==##@   #   @##==---==##@    #==-==#    @##==---==##@   #   @##==---==##
#=---==##@    #=#    @##==---==##@    #=#    @##==---==##@    #=#    @##==---=#
#--==##@    #==-==#    @##==---==##@   #   @##==---==##@    #==-==#    @##==--#
#==##@    #==-- --==#    @##==---==##@   @##==---==##@    #==-- --==#    @##==#
###@    #==--  :  --==#    @##==---==##@##==---==##@    #==--  :  --==#    @###
